export const FETCH_DATA_REQUEST = '[PERFECT DROPDOWN] FETCH DATA REQUEST';
export const FETCH_DATA_SUCCESS = '[PERFECT DROPDOWN] FETCH DATA SUCCESS';
export const FETCH_DATA_FAILURE = '[PERFECT DROPDOWN] FETCH DATA FAILURE';
export const CHOOSE_DATA = '[PERFECT DROPDOWN] CHOOSE DATA';