// APP CONFIGURATION KEYS

// PUBLIC API CONNECTED TO MOCKUP SERVICE ONLINE
export const SERVER_ADDRESS = 'https://64d3ae9e67b2662bf3dc9796.mockapi.io/api/v1/songs';

// COUNT OF DROPDOWN ELEMENTS
export const DROPDOWN_COUNT = 24;